### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by jazminebarroga** [granoff/Strongbox#19]
Any plans of supporting Swift Package Manager? 🙏

**Comment by granoff** [comment]
That would be a wonderful thing. Plans? Not at the moment. But I can add it to my list. Happy to take a pull request though (from anyone) to get it done in the meantime.

**Comment by remystr** [comment]
This can be closed due to merge of #20,
@granoff Can you make a new tag with this merge?

**Comment by granoff** [comment]
Done!
