### ISSUE TITLE
No support for iOS 9

### ISSUE THREAD

**Issue by Prince2k3** [granoff/Strongbox#2]
I know this can work with iOS 9 but I can't get it to with the deployment only set for iOS 10 on cocoapods spec.

**Comment by metisdev** [comment]
Would you reduce the IOS target to 9 in podspec? Is there any IOS 10 specific feature?

s.ios.deployment_target = '10.0'

**Comment by granoff** [comment]
Minimum iOS deployment target has been lowered to 9.0 beginning in v0.5.0, just published.
